name: New Project
description: Track the end-to-end process of ingesting a new dataset and associated workflows into the EMBER ecosystem.
title: Please enter a name for this project
labels:
  - "scope:project"
projects:
  - brain-bbqs/2
assignees:
  - CodyCBakerPhD
body:
  - type: input
    id: data-provider
    attributes:
      label: Data Provider / Contact Point
    validations:
      required: true
  - type: checkboxes
    id: kickoff-and-data-collection
    attributes:
      label: Kickoff & Data Collection
      options:
        - label: Outreach email has been sent
        - label: Kickoff meeting has been held
        - label: Initial data sample has been shared (data files for a single session)
        - label: Full dataset has been shared (all relevant data files for the project)
        - label: All associated processing and analysis scripts have been shared
        - label: Code or descriptions have been provided for all figures from the corresponding manuscript(s)
  - type: checkboxes
    id: planning-and-determination
    attributes:
      label: Planning & Determination
      options:
        - label: Data format determined
        - label: Required engagement with DSWG?
        - label: Archive target (EMBER-Public or EMBER-Vault) determined
        - label: Required engagement with ELSI?
  - type: checkboxes
    id: data-standardization-and-curation
    attributes:
      label: Data Standardization & Curation
      options:
        - label: Initial data sample has been standardized
        - label: Initial data sample has been validated
        - label: Initial data sample has been uploaded to target archive
        - label: Initial data sample has been reviewed by a curator
        - label: Full dataset has been standardized
        - label: Full dataset has been validated
        - label: Full dataset has been uploaded to target archive
        - label: Full dataset has been reviewed by a curator

