name: Dataset Onboarding
description: Track the end-to-end process of onboarding a new dataset into the EMBER archive
title: "[Dataset Onboarding] - "
labels:
  - onboarding
body:
  - type: input
    id: dataset-name
    attributes:
      label: Dataset Name
    validations:
      required: true
  - type: input
    id: data-provider
    attributes:
      label: Data Provider / Contact
    validations:
      required: true
  - type: input
    id: target-completion-date
    attributes:
      label: Target Completion Date
    validations:
      required: false
  - type: checkboxes
    id: kickoff-and-data-collection
    attributes:
      label: Kickoff & Data Collection
      options:
        - label: Kickoff meeting has been held
        - label: Initial data sample (single file)
        - label: Full dataset shared (all relevant data files)
        - label: All associated analysis scripts
        - label: Code or descriptions have been provided for all figures from the corresponding manuscript(s)
  - type: checkboxes
    id: planning-and-determination
    attributes:
      label: Planning & Determination
      options:
        - label: Data format determined
        - label: Required engagement with DSWG?
        - label: Archive target (EMBER-Public or EMBER-Vault) determined
        - label: Required engagement with ELSI?
  - type: checkboxes
    id: example-data-processing
    attributes:
      label: Example Data Processing
      options:
        - label: Example
