name: New Project
description: Track the end-to-end process of ingesting a new dataset and associated workflows into the EMBER ecosystem.
title: Please enter a name for this project
labels:
  - "scope:project"
projects:
  - brain-bbqs/2
assignees:
  - CodyCBakerPhD
body:
  - type: input
    id: data-provider
    attributes:
      label: Data Provider / Contact
    validations:
      required: true
  - type: textarea
    id: ingest-checklist
    attributes:
      label: Dataset Ingest Checklist
      value: |
        **Dataset Name:**
        **Data Provider / Contact:**
        **Target Completion Date:**

        ### Kickoff & Data Collection

        - [ ] Outreach email has been sent
        - [ ] Questionnaire has been filled out
        - [ ] Kickoff meeting has been held
        - [ ] Initial data sample (single file)
        - [ ] Full dataset shared (all relevant data files)
        - [ ] All associated analysis scripts
          - [ ] Code or descriptions have been provided for all figures from the corresponding manuscript(s)

        ### Planning & Determination

        - [ ] Data format determined
          - [ ] Required engagement with DSWG?
        - [ ] Archive target (EMBER-Public or EMBER-Vault) determined
          - [ ] Required engagement with ELSI?

        ### Example Data Processing

        - [ ] Example data standardized
        - [ ] Example data curated
          - [ ] Validation or inspection reports are verified
          - [ ] Suggestions for improvement have been provided
          - [ ] All suggestions for improvement have been addressed

        ### Full Dataset Processing

        - [ ] Full dataset standardized
        - [ ] Full dataset curated
          - [ ] Organization style and/or BIDS dataset metadata has been verified
          - [ ] Dataset metadata has been verified
            - [ ] Funding information is linked
            - [ ] Relevant manuscripts or protocols are linked
            - [ ] IRB numbers or other ethical confirmation IDs are included

        ### Publication & Archiving

        - [ ] Full dataset has been uploaded to the determined archive
        - [ ] Full dataset has been published
          - [ ] DOI: [~~~ Please fill in before closing issue ~~~]

